[build]
  publish = "."
  command = "npm run build"

[[redirects]]
  from = "/seagull-game/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/seagull-game"
  to = "/"
  status = 200

[build.environment]
  NODE_VERSION = "18"